message_box/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :messages
  root to: "messages#new"

end

message_box/app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

message_box/app/models/message.rb
class Message < ActiveRecord::Base
end

message_box/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

message_box/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_admin!, except: [:new, :create, :show]
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:content, :name, :email)
    end
end

message_box/app/helpers/application_helper.rb
module ApplicationHelper
end

message_box/app/helpers/messages_helper.rb
module MessagesHelper
end

message_box/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <%= viewport_meta_tag %>
    <title><%= content_for?(:title) ? yield(:title) : "MessageBox" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.3.0/respond.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">MessageBox</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% unless signed_in?(:admin) %>
              <li><%= link_to "New Message", new_message_path %></li>
              <li><%= link_to "Login", new_admin_session_path %></li>
            <% else %>
              <li><%= link_to "Messages", messages_path %></li>
              <li><%= link_to "Logout", destroy_admin_session_path %></li>
            <% end %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <hr>
        <p>&copy; Blue Coding LLC, 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

message_box/app/views/messages/_form.html.erb
<%= form_for @message, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :email, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :content, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :content, rows: 5, :class => 'text_area form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  messages_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

message_box/app/views/messages/edit.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

message_box/app/views/messages/index.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.id %></td>
          <td><%= message.content %></td>
          <td><%= message.name %></td>
          <td><%= message.email %></td>
        <td><%=l message.created_at, format: :long %></td>
        <td>
          <%= link_to message_path(message), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_message_path(message), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to message_path(message), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_message_path,
            :class => 'btn btn-primary' %>

message_box/app/views/messages/new.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1>Please leave your message</h1>
</div>
<%= render :partial => 'form' %>

message_box/app/views/messages/show.html.erb
<%- model_class = Message -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:content) %></dt>
      <dd><pre class="prettyprint"><%= @message.content %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @message.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:email) %></dt>
      <dd><pre class="prettyprint"><%= @message.email %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              :back, :class => 'btn btn-default'  %>
  <% if signed_in?(:admin) %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                edit_message_path(@message), :class => 'btn btn-default' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                message_path(@message),
                :method => 'delete',
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>
  <% end %>
</div>